services:
  loki:
    image: grafana/loki:main-7bfb71d
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100:3100
      - 7946
      - 9095

  tempo:
    image: grafana/tempo:r268-049347c-2099-1
    container_name: tempo
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml

  mimir:
    image: grafana/mimir:r410-1bbffa50
    container_name: mimir
    restart: unless-stopped
    ports:
      - 9090:9090
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml

  grafana:
    image: grafana/grafana:nightly-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-true}
      - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING:-true}
    depends_on:
      loki:
        condition: service_started
      tempo:
        condition: service_started
      mimir:
        condition: service_started

  otel:
    image: otel/opentelemetry-collector-contrib:nightly-arm64
    container_name: otel
    restart: unless-stopped
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel/otel.yaml:/etc/otelcol/config.yaml
    depends_on:
      loki:
        condition: service_started
      tempo:
        condition: service_started
      mimir:
        condition: service_started
      grafana:
        condition: service_started

  # It won`t be used on this project
  promtail:
    image: grafana/promtail:3.6.11
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yml"]
