receivers:
  otlp: 
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs: 
             - job_name: "otel-collector"
               scrape_interval: 60s
               static_configs: 
                - targets: ["localhost:8888"]

processors: 
  batch:
  resources:
    attributes:
      - action: insert
        key: loki.resource,labels
        value: service.name, service.environment

exporters: 
  otlphttp/loki: 
    endpoint: http://loki:3100/otlp/v1/logs
    tls:
      insure: true
  otlp/tempo:
    endpoint: tempo:3200
    tls:
      insecure: true
  otlphttp/metrics: 
    endpoint: http://mimir:9090/otlp/v1/metrics
    tls:
      insecure: true
  prometheusremotewrite: 
    endpoint: http://mimir:9090/api/v1/push
    tls:
      insecure: true

extensions: 
  health_check:
  pprof: 
  zpages: 

services: 
  extension: [health_check, pprof, zpages]
  pipelines: 
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
       receivers: [otlp]
       processors: [batch]
       exporters: [prometheusremotewrite]